version: '3.1'
services:
  mongo:
    image: mongo
#    command: [--auth]
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
    ports:
    - "27017:27017"
