version: '3.8'
services:
#  keyMetrics:
#    image: key-metrics
#    restart: always
#    ports:
#      - "8102:8102"
#    depends_on:
#      - db
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
